name: cloud-virtualization-teamproject

services:
  cloud-trainer:
    container_name: cloud-virtualization-teamproject-app
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: cloud-virtualization-teamproject:cpu
    ports:
      - "8010:8000"
    volumes:
      - ./data:/app/data
      - ./3. Trainer/outputs:/app/3. Trainer/outputs
      - ./2. Scheduler/scheduler_state:/app/2. Scheduler/scheduler_state
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
